package autoservicio;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;


public class IntRegistros extends javax.swing.JFrame {

    private Connection conexion;
    
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono png.png"));
        return retValue;
    }
     
    public IntRegistros(Connection conexion) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.conexion = conexion;
        mostrar("autos");
        verificarConexion();
        
    }
    
    public void mostrar(String tabla){
        
        String sql = "select * from " + tabla;
        Statement st;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("clave");
        model.addColumn("linea");
        model.addColumn("marca");
        model.addColumn("tipo");
        model.addColumn("modelo");
        model.addColumn("cilindros");
        model.addColumn("motor");
        model.addColumn("puertas");
        model.addColumn("cambioaceite");
        model.addColumn("afinacion");
        model.addColumn("lavadoexterno");
        model.addColumn("lavadointerior");
        model.addColumn("lavadomotor");
        model.addColumn("servfrenos");
        model.addColumn("anticongelante");
        jTableTabla.setModel(model);
        
        jTableTabla.setDefaultEditor(Object.class, null);
        
        TableColumnModel columnModel = jTableTabla.getColumnModel();
        for (int i = 0; i < columnModel.getColumnCount(); i++) {
        columnModel.getColumn(i).setResizable(false);
        }
        
        String [] datos = new String[15];
        
        try{
            st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next())
            {
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                datos[11]=rs.getString(12);
                datos[12]=rs.getString(13);
                datos[13]=rs.getString(14);
                datos[14]=rs.getString(15);
                model.addRow(datos);
            }
            
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null,"Error" + e.toString());
        }
        
    }
    
    
    public void verificarConexion() {
    if (conexion != null) {
        System.out.println("SI");
    } else {
        System.out.println("NO");
    }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabla = new javax.swing.JTable();
        jLabelFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTROS");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(104, 104, 104));
        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setOpaque(false);

        jTableTabla.setBackground(new java.awt.Color(204, 204, 204));
        jTableTabla.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jTableTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableTabla.setOpaque(false);
        jTableTabla.setShowGrid(true);
        jScrollPane1.setViewportView(jTableTabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1180, 580));

        jLabelFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroRegistros 1200,600.jpg"))); // NOI18N
        getContentPane().add(jLabelFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new IntRegistros(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFONDO;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableTabla;
    // End of variables declaration//GEN-END:variables
}
